= TEST DRIVEN DEVELOPMENT on MINISHIFT
Welcome to my repo that houses reference doc for all things TDD on Openshift. To get started you will need to satisfy the following pre-reqs:

* https://www.okd.io/minishift[Minishifty]
* https://www.okd.io/download.html#oc-platforms[OC Client]
* https://www.virtualbox.org[Oracle Virtualbox]


=== Please FORK to retrieve the Source Code

Simply copy the https://github.com/jayatwork/tdd-on-minishift[GitHub repository URL] and pass it to the `git clone` command:

$ git clone https://github.com/jayatwork/tdd-on-minishift

 Next, switch to the project directory:

  $ cd tdd-on-minishift


=== Start minishift on Windows 7 (on oracle Virtual box)

 Navigate to install directory for minishift

  $ ./minishift start --vm-driver virtualbox

 Might be necessary to delete cache if experiencing VM startup issue

  $ ./minishift delete --clear-cache

 Upon sucessful startup you should see something this this:

  The server is accessible via web console at:
      https://<host>:8443/console

      You are logged in as:
          User:     developer
	  Password: <any value>

	  To login as administrator:
	  oc login -u system:admin

=== Deploy onto MINISHIFT

 Access console at url given on minishift startup 

 Copy login command and paste into termainl
 
  oc login https://<your_host>:8443 --token=<some_token_value>
  
== Commands to deploy on Openshift
* We must first create a ** Golang builder (base) image** pre-install, this is accomplished thru https://github.com/jayatwork/tdd-on-minishift/Dockerfile[dockerfile]
**NOTE**: required to do this as golang images require certain user privileges

----
$ oc new-app .minishift/templates/golang-builder.json -p SOURCE_REPOSITORY_URL=https://github.com/jayatwork/tdd-on-minishift.git
----
* A build will be started automatically. It might take some time.
You can run the command below to watch for builds:

----
$ oc get builds -w
----
* Once the build is running, follow the build logs:

----
$ oc logs -f bc/tdd-on-minishift
----
* Resources created in namespace include those below:

----


